# this workflow file builds and pushes the docker image to docker hub repository

name: Docker Image Build and Push

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:v0.11.1-rootless

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .  # Build from the root of the repository
          file: ./Dockerfile # Path to your Dockerfile (adjust if needed)
          push: true
          tags: ${{ secrets.DOCKER_REPO }}:${{ github.sha }}  # Tag with commit SHA
          build-args: | # Optional build arguments
            VERSION=${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Image digest
        id: image_digest
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_REPO }}:${{ github.sha }}

      - name: Print image digest
        run: |
          echo "Image digest: ${{ steps.image_digest.outputs.digest }}"
