name: Docker Image Build and Push to Dockerhub

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'sqlbot'
        required: true
      image_tag:
        description: '1.0.0'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:v0.11.1-rootless

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REPO }}/${{ github.event.inputs.image_name }}:${{ github.event.inputs.image_tag }}
          build-args: |
            VERSION=${{ github.sha }}  # Still include commit SHA as a build arg if needed
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Image digest
        id: image_digest
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_REPO }}/${{ github.event.inputs.image_name }}:${{ github.event.inputs.image_tag }}

      - name: Print image digest
        run: |
          echo "Image digest: ${{ steps.image_digest.outputs.digest }}"
