name: Trivy Scan

on:
  push:
    branches: [ "main" ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build Docker Image
        run: |
          docker build -t sqlbot:1.0 .

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget gnupg
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      - name: Run Trivy Scan
        run: |
          trivy image sqlbot:1.0 --format text > report.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: report.txt
