---
llm_model :  # LLM MODEL that you have selected in your GROQ platfrom
groq_api_key : 

sql_query_generator: 
  prompt : # prompt for sql query generation  goes here
  input :  # input needs to be the formm of list. Here you pass the inputs to the prompts
sql_query_interpreter:
  prompt : # prompts for sql query answer interpretation, returning the answer in the readaable format goes here
  input : # input needs to be the formm of list. Here you pass the inputs to the prompts
inspector  :
  prompt : # this is to check if the user's question is relevant to database or not and returns bool format, If the question is related to database, then returns True, otherwise False.
  input : # input needs to be the formm of list. Here you pass the inputs to the prompts
sentence_fix :
  prompt : # this prompt fixes the user's question grammatically
  input : # input needs to be the formm of list. Here you pass the inputs to the prompts


log:  
  prd :
    format : "%(asctime)s - %(levelname)s - %(name)s - %(filename)s:%(lineno)d - %(message)s"   # the format in which the log files will write the data
    stream_format : "%(asctime)s - %(levelname)s - %(message)s"  # the format in which log will be streamed
    filepath : log/  # the filepath, where logs will be stored


# GCP
default_credential_path : "secrets/cred.json"   # GOOGLE APPLICAITON DEFAULT AUTHETICATION KEY (json)
instance_conneciton_name : # the database conneciton name
DB_USER : # db user name  
DB_PASSWORD  : # password for the db user
DB_NAME : # database name
